### ISSUE TITLE
Symbol navigation

### ISSUE THREAD

**Issue by usakhelo** [HAG87/vscode-maxscript#2]
Hi,
I just wanted to ask if maxscript symbol navigation works with this extension?
I started to work on that feature some time ago but never finished - https://github.com/usakhelo/VSC_Maxscript
I'm very bad javascript/typescript but I could try to add that feature if it makes sense.

**Comment by HAG87** [comment]
Hi!. Just added basic support for symbol navigation.
I'm looking at your code and maybe I can make something with the Definition provider...
About your comment "should consider current scope somehow" and in the process add a complete set of features for outlining and so on, will need to adapt a complete lexer/parser for MaxScript, something I don't have the time availability to do it alone.
I will fork your repo and see if I can merge it with vscode-maxscript extension.
Regards

**Comment by usakhelo** [comment]
I'll check it first thing tomorrow, as well as your pr. Thanks! I look forward to replacing sublimetext with vscode!
