### ISSUE TITLE
Missing coloration

### ISSUE THREAD

**Issue by embeh** [HAG87/vscode-maxscript#3]
Just started to use VS Code (v1.24.1) and v1.8.3 of your MXS language extension (installed through the editor itself).

While most seems to be working, I am not getting syntax coloring for keywords such as 'fn', 'function', 'on', 'pressed', 'rollout', 'struct', 'getDir', 'setWaitCursor', 'setArrowCursor', 'macroScript' or 'format' (to name some examples). I do get coloring on other keywords, though.

What am I missing? 
FWIW, I am using the default dark theme.

**Comment by embeh** [comment]
FWIW, attached is a (non-functional) MAXScript file that shows issues with missing coloring as well as code collapsing.
[vs_code_bad_collapse_marks.zip](https://github.com/HAG87/vscode-maxscript/files/2115371/vs_code_bad_collapse_marks.zip)
![vs_code_screenshot](https://user-images.githubusercontent.com/3431046/41600597-a313795a-73d6-11e8-90fd-be752e5ac878.png)

**Comment by pepetd** [comment]
Extension description says there is also a customized theme and I do not see where to set-it, I am also missing coloration as stated above.

**Comment by kintolayli** [comment]
same issue!

**Comment by HAG87** [comment]
> same issue!

Please, refer to the extension README. There is an example of the configurations that needs to be added to the workspace/user settings.
